import { Calendar as CalendarIcon, Clock, Book } from 'lucide-react';

const schedule = [
  { time: '09:00 AM', subject: 'Machine Learning Basics', type: 'Video Tutor', duration: '1h' },
  { time: '10:30 AM', subject: 'Calculus Review', type: 'Quiz', duration: '30m' },
  { time: '02:00 PM', subject: 'React Context API', type: 'Ask AI', duration: '45m' },
];

export default function StudyPlanner() {
  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">AI Study Planner</h2>
          <p className="text-gray-500">Your personalized learning schedule generated by AI.</p>
        </div>
        <button className="bg-white border border-gray-200 text-gray-700 px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-50 hover:text-blue-600 transition-colors shadow-sm">
           Regenerate Plan
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Main Schedule */}
        <div className="lg:col-span-2 glass-card p-6">
           <div className="flex items-center justify-between mb-6 border-b border-gray-100 pb-4">
             <h3 className="font-semibold text-lg text-gray-900 flex items-center">
               <CalendarIcon className="w-5 h-5 text-blue-500 mr-2" />
               Today's Schedule
             </h3>
             <span className="text-sm bg-blue-100 text-blue-700 py-1 px-3 rounded-full font-medium">3 Tasks left</span>
           </div>

           <div className="space-y-6">
             {schedule.map((slot, index) => (
               <div key={index} className="flex relative">
                 {/* Timeline line */}
                 {index !== schedule.length - 1 && (
                   <div className="absolute left-4 top-8 bottom-[-24px] w-0.5 bg-gray-200"></div>
                 )}
                 
                 <div className="w-8 h-8 rounded-full bg-blue-100 border-4 border-white shadow-sm flex items-center justify-center relative z-10 flex-shrink-0 mt-1">
                   <div className="w-2.5 h-2.5 rounded-full bg-blue-500"></div>
                 </div>

                 <div className="ml-6 flex-1 bg-white border border-gray-100 rounded-2xl p-5 shadow-sm hover:shadow-md transition-shadow">
                    <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start gap-2">
                      <div>
                        <h4 className="font-semibold text-gray-900">{slot.subject}</h4>
                        <div className="flex items-center text-sm text-gray-500 mt-2 space-x-4">
                          <span className="flex items-center"><Clock className="w-4 h-4 mr-1 text-gray-400" /> {slot.time} ({slot.duration})</span>
                          <span className="flex items-center"><Book className="w-4 h-4 mr-1 text-gray-400" /> {slot.type}</span>
                        </div>
                      </div>
                      <button className="text-sm text-blue-600 font-medium hover:text-blue-800 bg-blue-50 px-3 py-1.5 rounded-lg transition-colors">Start Module</button>
                    </div>
                 </div>
               </div>
             ))}
           </div>
        </div>

        {/* AI Tips Sidebar */}
        <div className="space-y-6">
           <div className="bg-gradient-to-br from-orange-400 to-orange-500 rounded-2xl p-6 text-white shadow-md">
             <h3 className="font-semibold text-lg mb-2">Upcoming Exam</h3>
             <p className="text-orange-100 text-sm mb-4">Calculus Midterm - in 3 days!</p>
             <div className="w-full bg-black/20 rounded-full h-2 mb-2">
               <div className="bg-white h-2 rounded-full w-[80%]"></div>
             </div>
             <p className="text-xs text-orange-100 text-right">80% prepared</p>
           </div>

           <div className="glass-card p-6">
             <h3 className="font-medium text-gray-900 mb-4 text-sm uppercase tracking-wider">AI Study Tips</h3>
             <ul className="space-y-4">
               <li className="text-sm text-gray-600 flex items-start">
                 <span className="text-blue-500 mr-2 mt-0.5">•</span>
                 Take a 5-minute break after your Machine Learning module to improve retention.
               </li>
               <li className="text-sm text-gray-600 flex items-start">
                 <span className="text-blue-500 mr-2 mt-0.5">•</span>
                 Review Calculus formulas before bed tonight based on your recent quiz errors.
               </li>
             </ul>
           </div>
        </div>

      </div>
    </div>
  );
}
